version: '3'

services:

  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: iam
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root1234
